name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare output folder
        run: mkdir -p dist

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: KorkmazPro28
          outputs: dist/snake-base.svg

      - name: Apply custom styling (make it realistic)
        run: |
          sed -i 's/fill="#000000"/fill="#0A0F18"/g' dist/snake-base.svg
          sed -i 's/fill="#ebedf0"/fill="#1a1a1a"/g' dist/snake-base.svg
          sed -i 's/fill="#40c463"/fill="url(#snakeGrad)"/g' dist/snake-base.svg
          awk '/<svg/{print;print "<defs><linearGradient id=\"snakeGrad\" x1=\"0\" x2=\"1\"><stop offset=\"0\" stop-color=\"#39FF14\"/><stop offset=\"1\" stop-color=\"#004400\"/></linearGradient></defs>";next}1' dist/snake-base.svg > dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
